### ISSUE TITLE
Google maps navigation issue.

### ISSUE THREAD

**Issue by alexpennos** [Trevelopment/MZD-AIO#71]
Hello. I am using aa with a Samsung Note 9 woth android 10.
When in google maps, it looks like if i am always going backwards. Lile the compass is not working properly and shows that the car is pointing the wrong direction. This causes a constant re-routing with a very strange behavior. On waze, everything looks normal...

**Comment by kakistos153** [comment]
Having the same issue. 2014 Mazda 3.

**Comment by Tristan-cx5** [comment]
Have you tried to use the "Reverse Compass" functionality, which can be selected in AIO before compiling the AA Tweak - see bottom left for the checkbox. It helped, when I had that problem with an older AA version. You can install the new AA (with ticked checkbox) over the old AA version.

**Comment by alexpennos** [comment]
Hello Tristan.
Indeed this mase things better but not all the times it's usable. When maps are on screen and music is played (tune in, spotify or YT music) it is barely usable. It's glitcing, jumping, or loosing orientation but most of the time it freezes and I have to turn off the car, get out (so that it's not detecting my key) and get in again to restart it. Honestly it is so frustrating that I am thinking of getting it officially upgraded... :(

**Comment by iliyahoo** [comment]
Having the same issue too.
Cannot use Google maps or Waze, because of Head Unit crashes, freezes and restarts.

Samsung Note 9 with android 10 (Android Auto built-in).
Mazda 3 - 2019.

**Comment by alexpennos** [comment]
Same with me. Continuously crashing and restarting. Thought it was because of music being streamed in the meantime. Tried without any audio being streamed and the issues persisted.
Also on a Note 9 with Android Auto built-in on a mazda cx3 2016 with firmware 55xxxxx

**Comment by Trevelopment** [comment]
yes that is fixed by updating google play services https://github.com/gartnera/headunit/pull/174

**Comment by alexpennos** [comment]
> Having the same issue. 2014 Mazda 3.

Kakistos, are you from Greece?

**Comment by alexpennos** [comment]
> yes that is fixed by updating google play services [gartnera/headunit#174](https://github.com/gartnera/headunit/pull/174)

Thank you very much for your time, help and reply. I will try to update my google services hoping that this will resolve the issues.

**Comment by muammar** [comment]
I also am experiencing the same. I deleted restarted everything on the inforentertainment system and the problem is still there. My phone is a Pixel 3 XL. What else I could try to fix this? How can I help out with this?

**Comment by iliyahoo** [comment]
For those who has a smartphone with Android 10 version this package should help:
https://www.apkmirror.com/apk/google-inc/android-auto-for-phone-screens/android-auto-for-phone-screens-1-1-release/android-auto-for-phone-screens-1-1-android-apk-download/

**Comment by muammar** [comment]
@iliyahoo what you mean is that by installing this version one would stop facing the restarting problem?

**Comment by iliyahoo** [comment]
@muammar Android 10 has already preinstalled version of AA. After recent system upgrade, my AA  was constantly restarting. So I've uninstalled my AA by holding an AA icon. But that didn't resolve a problem. Now head unit can't start when I connect my phone.
After all only installing "AA for Phone Screens" fixed the issue and AA is working like before.

**Comment by muammar** [comment]
@iliyahoo ok, now I get it. That makes sense. I have installed and will report back when I get to try this out. I am glad I did not take the car to the service center because they wanted ~$400 to fix this.

**Comment by iliyahoo** [comment]
@muammar I'd like to mention, that this package was not available in the Play Store due to the country restriction and direct downloading to the phone from the link I mentioned above didn't work. So I downloaded it to my notebook and transferred to the phone with cable.

**Comment by muammar** [comment]
> @muammar I'd like to mention, that this package was not available in the Play Store due to the country restriction and direct downloading to the phone from the link I mentioned above didn't work. So I downloaded it to my notebook and transferred to the phone with cable.

Unfortunately, this did not work for me. I did the following: 

1. Remove the android auto that I had installed. 
2. Download the app you suggested above and installed it. 
3. When android auto started it said that I needed to update it. If no update happened then the app could not be used. 

@iliyahoo thanks anyways. I think the best solution I guess would be to update the Android Auto provided in MZD-AIO? Or the problem is somewhere else?

**Comment by Trevelopment** [comment]
@muammar did you update Google Play Services?

**Comment by muammar** [comment]
@Trevelopment I just did what I mentioned above. What version of Google play services should I install?

**Comment by Trevelopment** [comment]
Honestly, I don't know but what I do know is that updating it to the latest version solved the issue for everyone else.

**Comment by Trevelopment** [comment]
and clear the cache too

**Comment by muammar** [comment]
@Trevelopment it is my understanding that pixels are updated to latest versions. My Google play services version 20.06.16 (120400-296104215). Can anyone confirm that this version works? I

**Comment by Trevelopment** [comment]
I have the same version and it works clear the cache

**Comment by muammar** [comment]
> I have the same version and it works clear the cache

I will do that and report back again. If that does not work that might mean there is something else going on with my Mazda3.

**Comment by Matthew-Mel** [comment]
I have the same issue,  tried to upgrade AA to latest version and clean the cache,  still doesn't work.
