### ISSUE TITLE
AA issue: Can't connect to headunit process

### ISSUE THREAD

**Issue by MarioAM3** [Trevelopment/MZD-AIO#74]
"_startContextReady: Can't connect to headunit process" issue everytime I tried to connect my smartphone. I can see the same issue when I turn on the CMU without a smartphone connected.
In AIO 2.8.4 never happend before.

FW Version: 56.00.230
AIO Version: 2.8.5
Smartphone: Samsung Galaxy S7 (Android 8.0)

**Comment by Trevelopment** [comment]
On  your USB drive you used to install find `/bakups/AIO_log.log` and post that here

**Comment by MarioAM3** [comment]
> 
> 
> On your USB drive you used to install find `/bakups/AIO_log.log` and post that here

=========================================================================
=======================   START LOGGING TWEAKS...  ======================
======================= AIO v.2.8.5  -  2020.02.02 ======================
================ MAZ_CMU-150_56.00.230A  Flavor cmu150_EU ===============
======================= CMU_SW_VER = 56.00.230A-EU ======================
=======================  COMPATIBILITY_GROUP  = 1 =======================

=======================   MYDIR = /tmp/mnt/sdb1    ======================
==================      DATE = 03/04/20 19:54:02        =================
===         Copytest to sd card successful, mount point is OK         ===
 
=======        Detected compatible version 56.00.230A-EU          =======
 
======***********    BEGIN PRE-INSTALL OPERATIONS ...    **********======
================== Remounted /tmp/mnt/resources =========================
================== Backup of sm.conf.org already there! =================
=====================  Watchdog Already Disabled! =======================
================== Backup of opera.ini already there! ===================
============== Userjs & File Xmlhttprequest Already Enabled =============
======================= data_persist 99% used ===========================
======================== rootfs 82% used ================================
====================== resources 74% used ===============================
/mnt/sdb1/tweaks.sh: line 769: rm: Argument list too long
================== Over 80% Used Delete Dump Files  =====================
=========************ END PRE-INSTALL OPERATIONS ***************=========
 
====************  INSTALL ANDROID AUTO HEADUNIT APP v1.12...*********====
===                   Removed old Android Auto App                    ===
===      Added Android Auto entry to /jci/scripts/stage_wifi.sh       ===
cp: write error: No space left on device
cp: write error: No space left on device
cp: can't create '/tmp/mnt/data_persist/dev/bin/headunit.json': No space left on device
cp: can't create directory '/tmp/mnt/data_persist/dev/bin/headunit_libs': No space left on device
===                Copied Android Auto Headunit App files             ===
===           No additionalApps.js available, will copy one           ===
===                   Created additionalApps.json                     ===
===   /tmp/mnt/sdb1/config/bin/node add_app_json.js Android Au        ===
sed: /tmp/mnt/data_persist/dev/bin/headunit.json: No such file or directory
===                    Android Auto Reverse Heading                   ===
======================== rootfs 82% used ================================
====================== resources 74% used ===============================
======================= END OF TWEAKS INSTALLATION ======================

[AIO_log.log](https://github.com/Trevelopment/MZD-AIO/files/4289541/AIO_log.log)

**Comment by Trevelopment** [comment]
Interesting... my idea to delete the dump files fails when there are so many that the files exceed the limit of the delete command as we see here:
`/mnt/sdb1/tweaks.sh: line 769: rm: Argument list too long`
Then there is no room because those damn dump files are taking up all the room:
`cp: write error: No space left on device
cp: write error: No space left on device
cp: can't create '/tmp/mnt/data_persist/dev/bin/headunit.json': No space left on device
cp: can't create directory '/tmp/mnt/data_persist/dev/bin/headunit_libs': No space left on device`
would you mind replacing `tweaks.sh` with this file and post the log from that run:
[tweaks.txt](https://github.com/Trevelopment/MZD-AIO/files/4290431/tweaks.txt)
(rename it to tweaks.sh)  it should fix it so you won't have this issue ever again.

**Comment by MarioAM3** [comment]
> 
> 
> Interesting... my idea to delete the dump files fails when there are so many that the files exceed the limit of the delete command as we see here:
> `/mnt/sdb1/tweaks.sh: line 769: rm: Argument list too long`
> Then there is no room because those damn dump files are taking up all the room:
> `cp: write error: No space left on device cp: write error: No space left on device cp: can't create '/tmp/mnt/data_persist/dev/bin/headunit.json': No space left on device cp: can't create directory '/tmp/mnt/data_persist/dev/bin/headunit_libs': No space left on device`
> would you mind replacing `tweaks.sh` with this file and post the log from that run:
> [tweaks.txt](https://github.com/Trevelopment/MZD-AIO/files/4290431/tweaks.txt)
> (rename it to tweaks.sh) it should fix it so you won't have this issue ever again.

Hi,
I tried with your new Tweaks.sh but the issue still appears.

I attach the Log again here for more information:


=========================================================================
=======================   START LOGGING TWEAKS...  ======================
======================= AIO v.2.8.6  -  2020.04.04 ======================
================ MAZ_CMU-150_56.00.230A  Flavor cmu150_EU ===============
======================= CMU_SW_VER = 56.00.230A-EU ======================
=======================  COMPATIBILITY_GROUP  = 1 =======================

=======================   MYDIR = /tmp/mnt/sdb1    ======================
==================      DATE = 03/05/20 19:38:10        =================
===         Copytest to sd card successful, mount point is OK         ===
 
=======        Detected compatible version 56.00.230A-EU          =======
 
======***********    BEGIN PRE-INSTALL OPERATIONS ...    **********======
================== Remounted /tmp/mnt/resources =========================
================== Backup of sm.conf.org already there! =================
=====================  Watchdog Already Disabled! =======================
================== Backup of opera.ini already there! ===================
============== Userjs & File Xmlhttprequest Already Enabled =============
======================= data_persist 99% used ===========================
======================== rootfs 82% used ================================
====================== resources 74% used ===============================
========================= Delete Dump Files =============================
======================= data_persist 5% used ===========================
================= App Install Location set to resources =================
=========************ END PRE-INSTALL OPERATIONS ***************=========
 
====************  INSTALL ANDROID AUTO HEADUNIT APP v1.13...*********====
===                   Removed old Android Auto App                    ===
===      Added Android Auto entry to /jci/scripts/stage_wifi.sh       ===
===                Copied Android Auto Headunit App files             ===
===                Created Symlink To Resources Partition             ===
===           No additionalApps.js available, will copy one           ===
===                   Created additionalApps.json                     ===
===   /tmp/mnt/sdb1/config/bin/node add_app_json.js Android Au        ===
===                    Android Auto Reverse Heading                   ===
======================== rootfs 82% used ================================
====================== resources 74% used ===============================
======================= END OF TWEAKS INSTALLATION ======================


[AIO_log.log](https://github.com/Trevelopment/MZD-AIO/files/4294877/AIO_log.log)

**Comment by Trevelopment** [comment]
are you sure?  Because that looks like a successful install.  maybe try it again?   you should have no issues. see #78

**Comment by MarioAM3** [comment]
> are you sure? Because that looks like a successful install. maybe try it again? you should have no issues. see #78

Hi, I did the following steps:
-Install AA from AIO 2.8.5 to my usb drive.
-Replace tweaks.sh for the tweaks.sh file downloaded here (changing .txt to .sh).
-Install AA from my usb to my CMU (clean installation).
-Try using AA but the "can't connect" issue appears without a smartphone connected.

I will try again later, with an installation over the previous one.

**Comment by Trevelopment** [comment]
OK and you don't need to use the downloaded tweaks.sh file again, that was a one time fix and it will work from now on normally.

**Comment by MarioAM3** [comment]
> 
> 
> OK and you don't need to use the downloaded tweaks.sh file again, that was a one time fix and it will work from now on normally.

Hi, 
after several AA 1.12 (AIO 2.8.5) installations, the "can´t connect" issue is not present in the CMU/APPS/ANDROID AUTO option. But I tried to connect the smartphone with AA v5.1.5006 without luck. I downgrade to a previous AA version and I could connect my smartphone with the AA in my CMU. Sadly, after a CMU reboot, the "can´t connect" issue appears again. I will try next days for be sure that all it´s ok.
I attach the log file just for your information.

[AIO_log.log](https://github.com/Trevelopment/MZD-AIO/files/4300768/AIO_log.log)

**Comment by MarioAM3** [comment]
Hi,
After a few days testing AA, I can say that it already works perfectly.
Thank you.
